### PR TITLE
Check all tutorials are present in docs

### PR DESCRIPTION
**Pull request by billbrod**
This adds two small tests:
- For every notebook, check that it appears in (at least one) nblink file
- Check that we have the same number of nblink files as noteboks

These two tests together should test that all notebooks have a single nblink file associated with them, and there aren't any extra nblink files.

### CODE REVIEW

**Comment by billbrod** [comment]
closes #171

**Review by kbonnen — APPROVED** [review]
Ok.  I'm reminding myself what more complex pull requests look like (with CI, etc.).

The only changes here are to the .yml file.  It confirms that all the tutorials have an nblink file.  It also confirms there are not extra nblink files.

There are no other changes, yes?

**Comment by billbrod** [comment]
Okay, this is working now, ready for review.

**Review by lyndond — APPROVED** [review]
LGTM

**Pull request merged**
